# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncryp < Formula
  desc "Weak Cryptography for Learners"
  homepage ""
  version "0.3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nobishino/ncryp/releases/download/v0.3.0/ncryp_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "870515e785f15b35948995ab573444a26c31442fe0069ba0e779d09fbd76aab9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nobishino/ncryp/releases/download/v0.3.0/ncryp_0.3.0_Darwin_arm64.tar.gz"
    sha256 "4eaa984a3645a6156dc4e55261ee25191d1583c10f924c6737dd2046856ee59c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nobishino/ncryp/releases/download/v0.3.0/ncryp_0.3.0_Linux_x86_64.tar.gz"
    sha256 "06ccde85c04516bc9eefaf849bf18ed3c03916928b0281783600fd003d618971"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nobishino/ncryp/releases/download/v0.3.0/ncryp_0.3.0_Linux_arm64.tar.gz"
    sha256 "c6f16881f00f0f9bbc51c8f0b016d2051275a777cd0cdf91cb70c04d030191cd"
  end

  def install
    bin.install "ncryp"
  end

  test do
    system "#{bin}/ncryp --version"
  end
end
