# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncryp < Formula
  desc "Weak Cryptography for Learners"
  homepage ""
  version "0.2.8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nobishino/ncryp/releases/download/v0.2.8/ncryp_0.2.8_Darwin_x86_64.tar.gz"
    sha256 "216eeea59d5812547548dbedbecd928b3505f9fbaead8c91cba4f855ebd1b375"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nobishino/ncryp/releases/download/v0.2.8/ncryp_0.2.8_Darwin_arm64.tar.gz"
    sha256 "db24a38472a42c81edfc10b6249f05d8d31ec7b5a663df8bdc9e9ab0da564a24"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nobishino/ncryp/releases/download/v0.2.8/ncryp_0.2.8_Linux_x86_64.tar.gz"
    sha256 "43c1fd8f741b0af73dae6bd60b70f4bc7aaf12a1e421f4ee79e80fdf51bb90f6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nobishino/ncryp/releases/download/v0.2.8/ncryp_0.2.8_Linux_arm64.tar.gz"
    sha256 "5909f1ef7a905d3081ce09a41edb2bd8878c35029fe51d468e42cfc16215a333"
  end

  def install
    bin.install "ncryp"
  end

  test do
    system "#{bin}/ncryp --version"
  end
end
